name: Wiki Page Creator Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Wiki Content
        run: |
          # Add your commands to generate Wiki content here
          # For example, you might run a script to convert code comments to Markdown
          echo "Generating Wiki content..."

      - name: Upload to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ACTION_MAIL: kisaron5@gmail.com
          ACTION_NAME: Kishoredevops55
          OWNER: Kishoredevops55
          REPO_NAME: Docker-CI
          MD_FOLDER: 'docs/*'
          SKIP_MD: 'README.md'
          WIKI_PUSH_MESSAGE: 'Update Wiki content'
